### ISSUE TITLE
Can not compute DMR using computeDMRs function 

### ISSUE THREAD

**Issue by gourav924** [nrzabet/DMRcaller#12]
Hello, I am trying to compute DMR using the neighborhood method, but I am not able to do it. 

Below is the R code: 

chr_local <- GRanges(seqnames = Rle("Chr3"), ranges = IRanges(5E5,6E5))
DMRsNeighbourhoodCG <- computeDMRs(methylationDataList[["Control"]],
                                   methylationDataList[["Treated"]],
                                   regions = chr_local,
                                   context = "CG",
                                   method = "neighbourhood",
                                   test = "score",
                                   pValueThreshold = 0.01,
                                   minCytosinesCount = 4,
                                   minProportionDifference = 0.4,
                                   minGap = 200,
                                   minSize = 1,minReadsPerCytosine = 4,
                                   cores = 1)

Output: 
Parameters checking ...
Extract methylation in the corresponding context 
Computing DMRs 
> DMRsNeighbourhoodCG
GRanges object with 0 ranges and 0 metadata columns:
   seqnames    ranges strand
      <Rle> <IRanges>  <Rle>
  -------
  seqinfo: no sequences

I do not know what does it mean, all the input files are the CX_report.txt from bismark. 

Can anyone tell, me what's wrong with my code

Thanks in advance

**Comment by nrzabet** [comment]
If it didn't generate any error then there is nothing wrong with the code. The tool detects no DMRs with the parameters you selected. You might need to relax those parameters to detect DMRs, or look in a bigger region. 

One suggestion is to use
```
pValueThreshold = 0.05,
minCytosinesCount = 1,
minProportionDifference = 0.2,
```
