### ISSUE TITLE
Error for genome wide CHH DMRs

### ISSUE THREAD

**Issue by supermaxiste** [nrzabet/DMRcaller#3]
Hi,

I'm running a genome wide DMR analysis for CHH with `computeDMRsReplicates` as follows :
```
DMRsReplicatesBinsCHH <- computeDMRsReplicates(methylationData = methylationDataList,
                                            condition = condition,
                                            regions = NULL,
                                            context = "CHH",
                                            method = "bins",
                                            binSize = 100,
                                            test = "betareg",
                                            pseudocountM = 1,
                                            pseudocountN = 2,
                                            pValueThreshold = 0.05,
                                            minCytosinesCount = 1,
                                            minProportionDifference = 0.1,
                                            minGap = 200,
                                            minSize = 50,
                                            minReadsPerCytosine = 3,
                                            cores = 8)
```

This is the output I get at first:

```
Reading file: /path/to/file1.txt
Finished reading file: /path/to/file1.txt
Reading file: /path/to/file2.txt
Finished reading file: /path/to/file2.txt
Reading file: /path/to/file3.txt
Finished reading file: /path/to/file3.txt
Reading file: /path/to/file4.txt
Finished reading file: /path/to/file4.txt
Validating objects 
Finding overlaps 
Joining objects 
Validating objects 
Finding overlaps 
Joining objects 
Validating objects 
Finding overlaps 
Joining objects 
Parameters checking ...
Extract methylation in the corresponding context 
Compute the DMRs using  8 cores
Computing DMRs at  scaffold_2240:3..6771232 
Computing DMRs at  scaffold_2449:37890..101038 
Computing DMRs at  scaffold_2658:11660..15546 
Computing DMRs at  scaffold_2868:928..7400 
Computing DMRs at  scaffold_3077:2146..4290 
Count inside each bin...
Computing DMRs at  scaffold_3286:2207..2520 
Computing DMRs at  scaffold_3496:451..1793 
Count inside each bin...
Filter the bins...
Identifying DMRs...
Computing DMRs at  scaffold_3705:844..1349 
Count inside each bin...
Filter the bins...
Identifying DMRs...
Count inside each bin...
Filter the bins...
Identifying DMRs...
Count inside each bin...
Count inside each bin...
Filter the bins...
Filter the bins...
Identifying DMRs...
Computing DMRs at  scaffold_3287:7..2523 
```

So it looks like it's running fine but then I get an error. With`traceback()`:

```
Computing DMRs at  scaffold_3496:4..450 
Count inside each bin...
Filter the bins...
11: (function () 
    traceback(2))()
10: stop("all elements in '...' must be GRanges objects")
9: (function (...) 
   {
       listData <- list(...)
       if (length(listData) == 1L && !is(listData[[1L]], "GRanges")) 
           return(as(listData[[1L]], "CompressedGRangesList", strict = FALSE))
       if (length(listData) == 0L) {
           unlistData <- GRanges()
       }
       else {
           if (!all(sapply(listData, is, "GRanges"))) 
               stop("all elements in '...' must be GRanges objects")
           unlistData <- suppressWarnings(do.call("c", unname(listData)))
       }
       relist(unlistData, listData)
   })("Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       new("GRanges", seqnames = new("Rle", values = integer(0), 
           lengths = integer(0), elementMetadata = NULL, metadata = list()), 
           ranges = new("IRanges", start = integer(0), width = integer(0), 
               NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
               metadata = list()), strand = new("Rle", values = integer(0), 
               lengths = integer(0), elementMetadata = NULL, metadata = list()), 
           seqinfo = new("Seqinfo", seqnames = c("scaffold_2240", 
           "scaffold_2241", "scaffold_2242", "scaffold_2243", "scaffold_2244", 
           this list goes on for a while), seqlengths = c(NA_integer_, 
           NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
           this list goes on for a while), 
               is_circular = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()), new("GRanges", 
           seqnames = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), ranges = new("IRanges", 
               start = integer(0), width = integer(0), NAMES = NULL, 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           strand = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), seqinfo = new("Seqinfo", 
               seqnames = c("scaffold_2240", "scaffold_2241", "scaffold_2242", 
               "scaffold_2243", "scaffold_2244", "scaffold_2245", 
               this list goes on for a while), seqlengths = c(NA_integer_, NA_integer_, 
               NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
               this list goes on for a while), is_circular = c(NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()), new("GRanges", 
           seqnames = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), ranges = new("IRanges", 
               start = integer(0), width = integer(0), NAMES = NULL, 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           strand = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), seqinfo = new("Seqinfo", 
               seqnames = c("scaffold_2240", "scaffold_2241", "scaffold_2242", 
               "scaffold_2243", "scaffold_2244", "scaffold_2245", 
               this list goes on for a while), seqlengths = c(NA_integer_, NA_integer_, 
               NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
               this list goes on for a while), is_circular = c(NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()))
8: do.call(GRangesList, from)
7: do.call(GRangesList, from)
6: asMethod(object, strict = FALSE)
5: as(listData[[1L]], "CompressedGRangesList", strict = FALSE)
4: GRangesList(computedDMRs)
3: unlist(GRangesList(computedDMRs))
2: .computeDMRsReplicatesBins(methylationData = methylationData, 
       condition = condition, regions = regions, context = context, 
       binSize = binSize, pseudocountM = pseudocountM, pseudocountN = pseudocountN, 
       pValueThreshold = pValueThreshold, minCytosinesCount = minCytosinesCount, 
       minProportionDifference = minProportionDifference, minGap = minGap, 
       minSize = minSize, minReadsPerCytosine = minReadsPerCytosine, 
       cores = cores)
1: computeDMRsReplicates(methylationData = methylationDataList, 
       condition = condition, regions = NULL, context = "CHH", method = "bins", 
       binSize = 100, test = "betareg", pseudocountM = 1, pseudocountN = 2, 
       pValueThreshold = 0.05, minCytosinesCount = 1, minProportionDifference = 0.1, 
       minGap = 200, minSize = 50, minReadsPerCytosine = 3, cores = 8)
8: (function () 
   traceback(2))()
7: as.data.frame(DMRsReplicatesBinsCHH)
6: is.data.frame(x)
5: write.table(as.data.frame(DMRsReplicatesBinsCHH), file = "filename.csv", 
       col.names = NA, sep = ",", dec = ".", qmethod = "double")
4: eval(expr, p)
3: eval(expr, p)
2: eval.parent(Call)
1: write.csv(as.data.frame(DMRsReplicatesBinsCHH), file = "filename.csv")

```

I see a lot of zeros and NA in the error message so could it be that I don't have any DMRs? 

Thank you (again) for the help!

Stefan

**Comment by nrzabet** [comment]
Hi Stefan, 

It was not clear, do you get the error message when you run computeDMRsReplicates? or that function call finishes well? 

Radu

**Comment by supermaxiste** [comment]
Hi Radu,

I realized that the function `computeDMRsReplicates` seems to be working fine, but when I try to export the results I get in csv format, it doesn't seem to be working. I already tried using `as.data.frame(DMRsReplicatesBinsCHH)` and `as(DMRsReplicatesBinsCHH, "dataframe")`, but got a similar error to the one shown before.

Is there a suggested way to export this GRanges object?

Best,
Stefan

**Comment by nrzabet** [comment]
If you print the GRanges object, how does it look like?

Radu

**Comment by nrzabet** [comment]
BTW: I usually use export function from rtracklayer to save the DMRs as bed files.

**Comment by supermaxiste** [comment]
Hi Radu,

it appears that `ComputeDMRsReplicates` is giving an error:

```
11: (function () 
    traceback(2))()
10: stop("all elements in '...' must be GRanges objects")
9: (function (...) 
   {
       listData <- list(...)
       if (length(listData) == 1L && !is(listData[[1L]], "GRanges")) 
           return(as(listData[[1L]], "CompressedGRangesList", strict = FALSE))
       if (length(listData) == 0L) {
           unlistData <- GRanges()
       }
       else {
           if (!all(sapply(listData, is, "GRanges"))) 
               stop("all elements in '...' must be GRanges objects")
           unlistData <- suppressWarnings(do.call("c", unname(listData)))
       }
       relist(unlistData, listData)
   })("Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       "Error in FUN(X[[i]], ...) : object 'DMRs' not found\n", 
       new("GRanges", seqnames = new("Rle", values = integer(0), 
           lengths = integer(0), elementMetadata = NULL, metadata = list()), 
           ranges = new("IRanges", start = integer(0), width = integer(0), 
               NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
               metadata = list()), strand = new("Rle", values = integer(0), 
               lengths = integer(0), elementMetadata = NULL, metadata = list()), 
           seqinfo = new("Seqinfo", seqnames = c("scaffold_2240", 
           "scaffold_2241", "scaffold_2242", "scaffold_2243", "scaffold_2244", 
           this list goes on for a while), seqlengths = c(NA_integer_, 
           NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
           this list goes on for a while), 
               is_circular = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()), new("GRanges", 
           seqnames = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), ranges = new("IRanges", 
               start = integer(0), width = integer(0), NAMES = NULL, 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           strand = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), seqinfo = new("Seqinfo", 
               seqnames = c("scaffold_2240", "scaffold_2241", "scaffold_2242", 
               "scaffold_2243", "scaffold_2244", "scaffold_2245", 
               this list goes on for a while), seqlengths = c(NA_integer_, NA_integer_, 
               NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
               this list goes on for a while), is_circular = c(NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()), new("GRanges", 
           seqnames = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), ranges = new("IRanges", 
               start = integer(0), width = integer(0), NAMES = NULL, 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           strand = new("Rle", values = integer(0), lengths = integer(0), 
               elementMetadata = NULL, metadata = list()), seqinfo = new("Seqinfo", 
               seqnames = c("scaffold_2240", "scaffold_2241", "scaffold_2242", 
               "scaffold_2243", "scaffold_2244", "scaffold_2245", 
               this list goes on for a while), seqlengths = c(NA_integer_, NA_integer_, 
               NA_integer_, NA_integer_, NA_integer_, NA_integer_, 
               this list goes on for a while), is_circular = c(NA, NA, NA, NA, NA, 
               this list goes on for a while), genome = c(NA_character_, 
               NA_character_, NA_character_, NA_character_, NA_character_, 
               this list goes on for a while)), elementMetadata = new("DataFrame", 
               rownames = NULL, nrows = 0L, listData = list(sumReadsM1 = numeric(0), 
                   sumReadsN1 = numeric(0), proportion1 = numeric(0), 
                   sumReadsM2 = numeric(0), sumReadsN2 = numeric(0), 
                   proportion2 = numeric(0), cytosinesCount = numeric(0), 
                   proportionsR1 = numeric(0), proportionsR2 = numeric(0), 
                   proportionsR3 = numeric(0), proportionsR4 = numeric(0)), 
               elementType = "ANY", elementMetadata = NULL, metadata = list()), 
           elementType = "ANY", metadata = list()))
8: do.call(GRangesList, from)
7: do.call(GRangesList, from)
6: asMethod(object, strict = FALSE)
5: as(listData[[1L]], "CompressedGRangesList", strict = FALSE)
4: GRangesList(computedDMRs)
3: unlist(GRangesList(computedDMRs))
2: .computeDMRsReplicatesBins(methylationData = methylationData, 
       condition = condition, regions = regions, context = context, 
       binSize = binSize, pseudocountM = pseudocountM, pseudocountN = pseudocountN, 
       pValueThreshold = pValueThreshold, minCytosinesCount = minCytosinesCount, 
       minProportionDifference = minProportionDifference, minGap = minGap, 
       minSize = minSize, minReadsPerCytosine = minReadsPerCytosine, 
       cores = cores)
1: computeDMRsReplicates(methylationData = methylationDataList, 
       condition = condition, regions = NULL, context = "CHH", method = "bins", 
       binSize = 100, test = "betareg", pseudocountM = 1, pseudocountN = 2, 
       pValueThreshold = 0.05, minCytosinesCount = 1, minProportionDifference = 0.1, 
       minGap = 200, minSize = 50, minReadsPerCytosine = 3, cores = 8)
```

This is then causing the export error because no object is created by `ComputeDMRsReplicates`.

**Comment by supermaxiste** [comment]
Also, as mentioned before the function runs for a while and performs operations on bins:

```
Parameters checking ...
Extract methylation in the corresponding context 
Compute the DMRs using  8 cores
Computing DMRs at  scaffold_2240:3..6771232 
Computing DMRs at  scaffold_2449:37890..101038 
Computing DMRs at  scaffold_2658:11660..15546 
Computing DMRs at  scaffold_2868:928..7400 
Computing DMRs at  scaffold_3077:2146..4290 
Count inside each bin...
Computing DMRs at  scaffold_3286:2207..2520 
Computing DMRs at  scaffold_3496:451..1793 
Count inside each bin...
Filter the bins...
Identifying DMRs...
Computing DMRs at  scaffold_3705:844..1349 
Count inside each bin...
Filter the bins...
Identifying DMRs...
Count inside each bin...
Filter the bins...
Identifying DMRs...
Count inside each bin...
Count inside each bin...
Filter the bins...
Filter the bins...
Identifying DMRs...
Computing DMRs at  scaffold_3287:7..2523
etc.
```

Then at some point `ComputeDMRsReplicates` gives that error. Let me know if you need more details.

Best,
Stefan

**Comment by nrzabet** [comment]
I was wondering if you run this with cores=1 are you still getting the same error?

**Comment by supermaxiste** [comment]
Hi Radu,

the error is slightly different:

```
Parameters checking ...
Extract methylation in the corresponding context
Computing DMRs at  scaffold_1:1..4302262
Count inside each bin...
Filter the bins...
Identifying DMRs...
Error in FUN(X[[i]], ...) : object 'DMRs' not found
Calls: computeDMRsReplicates ... .computeDMRsReplicatesBins -> lapply -> lapply -> FUN
6: (function ()
   traceback(2))()
5: FUN(X[[i]], ...)
4: lapply(1:length(regionsList), .computeDMRsReplicatesBinsLoop)
3: lapply(1:length(regionsList), .computeDMRsReplicatesBinsLoop)
2: .computeDMRsReplicatesBins(methylationData = methylationData,
       condition = condition, regions = regions, context = context,
       binSize = binSize, pseudocountM = pseudocountM, pseudocountN = pseudocountN,
       pValueThreshold = pValueThreshold, minCytosinesCount = minCytosinesCount,
       minProportionDifference = minProportionDifference, minGap = minGap,
       minSize = minSize, minReadsPerCytosine = minReadsPerCytosine,
       cores = cores)
1: computeDMRsReplicates(methylationData = methylationDataList,
       condition = condition, regions = NULL, context = "CHH", method = "bins",
       binSize = 100, test = "betareg", pseudocountM = 1, pseudocountN = 2,
       pValueThreshold = 0.05, minCytosinesCount = 1, minProportionDifference = 0.1,
       minGap = 200, minSize = 50, minReadsPerCytosine = 3, cores = 1)
```

**Comment by nrzabet** [comment]
I was wondering whether it is possible to share a sample of the data so I can try debugging it? just a part of the methylationDataList as an RData object

**Comment by supermaxiste** [comment]
Dear Radu,

you can find the methylationDataList object [here](https://1drv.ms/f/s!AmvMKfVo3Z7fiJZDc_UMhJw28Nq3vg). 

Thank you a lot for the help!

Stefan

**Comment by nrzabet** [comment]
I have just tried to code and I don't seem to get the error (see below).  Just an empty list of DMRs

`
condition <- c("a", "a", "b", "b")
methylationDataList <- readRDS("~/Downloads/methylationDataList.rds")
DMRsReplicatesBinsCHH <- computeDMRsReplicates(methylationData = methylationDataList,
                                               condition = condition,
                                               regions = NULL,
                                               context = "CHH",
                                               method = "bins",
                                               binSize = 100,
                                               test = "betareg",
                                               pseudocountM = 1,
                                               pseudocountN = 2,
                                               pValueThreshold = 0.05,
                                               minCytosinesCount = 1,
                                               minProportionDifference = 0.1,
                                               minGap = 200,
                                               minSize = 50,
                                               minReadsPerCytosine = 3,
                                               cores = 8)
Parameters checking ...
Extract methylation in the corresponding context 
Compute the DMRs using  8 cores
DMRsReplicatesBinsCHH
GRanges object with 0 ranges and 9 metadata columns:
   seqnames    ranges strand | sumReadsM1 sumReadsN1 proportion1 sumReadsM2 sumReadsN2 proportion2 cytosinesCount     context direction
      <Rle> <IRanges>  <Rle> |  <numeric>  <numeric>   <numeric>  <numeric>  <numeric>   <numeric>      <numeric> <character> <numeric>
  -------
  seqinfo: 2239 sequences from an unspecified genome; no seqlengths
`

**Comment by nrzabet** [comment]
I forgot to ask, what version of DMRcaller do you have and what is the R version?

**Comment by supermaxiste** [comment]
Hi Radu,

thank you for the feedback. R version is `3.5.1` while DMRcaller version is `1.14.1`. I'll see if I can get any DMR with different parameters then, it's strange that no DMRs appear.

Stefan

**Comment by e-tomato** [comment]
Hello Radu,
I get a same error when I run `computeDMRsReplicates` specially for CHH context using the same GRange object  "au_ch2" performed for CG and CHG DMR analysis.  The message is below:

> DMRsReplicatesBinsCHH.ch2=computeDMRsReplicates(methylationData=au_ch2, condition=c("a","a","b","b"), regions=NULL, context="CHH", method="bins", binSize=100, test="betareg", pseudocountM=1, pseudocouParameters checking ...0.01, minCytosinesCount=4, minProportionDifference=0.3, minGap=50, minSize=50, minReadsPerCytosine=4, cores=20)
> Extract methylation in the corresponding context
> Compute the DMRs using  20 cores
> Computing DMRs at  SL2.40ch02:3..2495916
> Computing DMRs at  SL2.40ch02:2495917..4991830
> Computing DMRs at  SL2.40ch02:4991831..7487744
> Computing DMRs at  SL2.40ch02:7487745..9983659
> Computing DMRs at  SL2.40ch02:9983660..12479573
> Computing DMRs at  SL2.40ch02:12479574..14975487
> Computing DMRs at  SL2.40ch02:14975488..17471402
> Computing DMRs at  SL2.40ch02:17471403..19967316
> Computing DMRs at  SL2.40ch02:19967317..22463230
> Computing DMRs at  SL2.40ch02:22463231..24959145
> Computing DMRs at  SL2.40ch02:24959146..27455059
> Computing DMRs at  SL2.40ch02:27455060..29950973
> Count inside each bin...
> Count inside each bin...
> Computing DMRs at  SL2.40ch02:29950974..32446887
> Count inside each bin...
> Count inside each bin...
> Computing DMRs at  SL2.40ch02:32446888..34942802
> Computing DMRs at  SL2.40ch02:34942803..37438716
> Computing DMRs at  SL2.40ch02:37438717..39934630
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Computing DMRs at  SL2.40ch02:39934631..42430545
> Count inside each bin...
> Count inside each bin...
> Computing DMRs at  SL2.40ch02:42430546..44926459
> Computing DMRs at  SL2.40ch02:44926460..47422373
> Computing DMRs at  SL2.40ch02:47422374..49918288
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Count inside each bin...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Filter the bins...
> Filter the bins...
> Identifying DMRs...
> Identifying DMRs...
> Filter the bins...
> Filter the bins...
> Identifying DMRs...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Filter the bins...
> Identifying DMRs...
> Error in (function (...)  : all elements in '...' must be GRanges objects
> In addition: Warning message:
> In parallel::mclapply(1:length(regionsList), .computeDMRsReplicatesBinsLoop,  :
>   scheduled core 1, 5 encountered error in user code, all values of the job will be affected.

Print au_ch2

> GRanges object with 15887536 ranges and 10 metadata columns:
>                seqnames    ranges strand |  context   readsM1   readsN1
>                   <Rle> <IRanges>  <Rle> | <factor> <integer> <integer>
>          [1] SL2.40ch02         3      - |      CHH         0         0
>          [2] SL2.40ch02         6      - |      CHH         0         0
>          [3] SL2.40ch02         9      - |      CHH         0         0
>          [4] SL2.40ch02        11      + |       CG        11        58
>          [5] SL2.40ch02        12      - |       CG         0         0
>          ...        ...       ...    ... .      ...       ...       ...
>   [15887532] SL2.40ch02  49918275      + |      CHH         0         0
>   [15887533] SL2.40ch02  49918276      + |      CHH         0         0
>   [15887534] SL2.40ch02  49918278      + |      CHH         0         0
>   [15887535] SL2.40ch02  49918286      - |      CHH         0         0
>   [15887536] SL2.40ch02  49918288      - |      CHH         0         0
>                readsM2   readsN2   readsM3   readsN3   readsM4   readsN4
>              <integer> <integer> <integer> <integer> <integer> <integer>
>          [1]         0         0         0         0         0         0
>          [2]         0         0         0         0         0         0
>          [3]         0         0         0         0         0         0
>          [4]        13        46        14        50        12        63
>          [5]         0         0         0         0         0         0
>          ...       ...       ...       ...       ...       ...       ...
>   [15887532]         0         0         0         1         0         0
>   [15887533]         0         0         0         1         0         0
>   [15887534]         0         0         0         0         0         0
>   [15887535]         0         0         0         0         1         1
>   [15887536]         0         0         0         0         0         1
>              trinucleotide_context
>                           <factor>
>          [1]                   CAT
>          [2]                   CAT
>          [3]                   CAT
>          [4]                   CGA
>          [5]                   CGT
>          ...                   ...
>   [15887532]                   CCA
>   [15887533]                   CAC
>   [15887534]                   CAA
>   [15887535]                   CTA
>   [15887536]                   CTC
>   -------
>   seqinfo: 13 sequences from an unspecified genome; no seqlengths
> 

VERSION
> sessionInfo()

> R version 3.5.3 (2019-03-11)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: /tools/R/R-3.5.3/lib64/R/lib/libRblas.so
> LAPACK: /tools/R/R-3.5.3/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets
> [8] methods   base
> 
> other attached packages:
> [1] dplyr_0.8.3          betareg_3.1-2        DMRcaller_1.14.2
> [4] GenomicRanges_1.34.0 GenomeInfoDb_1.18.2  IRanges_2.16.0
> [7] S4Vectors_0.20.1     BiocGenerics_0.28.0
> 
> loaded via a namespace (and not attached):
>  [1] flexmix_2.3-15         Rcpp_1.0.2             Formula_1.2-3
>  [4] magrittr_1.5           XVector_0.22.0         zlibbioc_1.28.0
>  [7] tidyselect_0.2.5       RcppRoll_0.3.0         lattice_0.20-38
> [10] R6_2.4.0               rlang_0.4.0            nnet_7.3-12
> [13] grid_3.5.3             modeltools_0.2-22      assertthat_0.2.1
> [16] lmtest_0.9-37          tibble_2.1.1           crayon_1.3.4
> [19] GenomeInfoDbData_1.2.0 purrr_0.3.2            bitops_1.0-6
> [22] RCurl_1.95-4.12        glue_1.3.1             sandwich_2.5-1
> [25] pillar_1.3.1           compiler_3.5.3         pkgconfig_2.0.2
> [28] zoo_1.8-6
> 

Could you help to figure out the problem?
Thanks very much.

**Comment by nrzabet** [comment]
Hi, 

I notice you are using an older version of the package. Can you update to the most recent one and try your code again?

If the code generates the same error, I was wondering if you could try to use single core and run the algorithm one chromosome at a time (using a for loop)? Then let me know where it crashes.

Radu
