### ISSUE TITLE
JoinReplicates for more than two methylation data sets

### ISSUE THREAD

**Issue by fbalao** [nrzabet/DMRcaller#4]
I would like to join more than two replicates at once (32). Is there any way?

**Comment by nrzabet** [comment]
Dear Francisco, 

You can do this by using a for loop to join them iteratively. 

Radu

**Comment by fbalao** [comment]
Yes, thanks. It worked like a charm. Here my code for other interested people:
```
# ind is the number of replicates -1
    methylationDataRep<-joinReplicates(methylationData[[1]], methylationData[[2]]) 
  for (h in 2:ind) { 
    methylationDataRep<-joinReplicates(methylationDataRep, methylationData[[h+1]])
  }
```

**Comment by hechuweiran** [comment]
it's error
> DataRep<-joinReplicates(methylationDataList[[1]], methylationDataList[[2]]) 
> DataRep <- joinReplicates(DataRep,methylationDataList[[3]])
Validating objects 
Finding overlaps 
Joining objects 
Error in DataFrame(..., check.names = FALSE) : 
  different row counts implied by arguments
In addition: Warning message:
In joinReplicates(DataRep, methylationDataList[[3]]) :
  The number of elements in each dataset is different,
            non replicated data will be dropped
