### ISSUE TITLE
DMRcaller: R crashing

### ISSUE THREAD

**Issue by sanchari24** [nrzabet/DMRcaller#8]
Hello,
I am using DMRcaller for genome wide DNA methylation. However, it always crashes while using the "computeDMRs" function. Kindly help.

`> methylationDataWT <- readBismark("M82_0h_CHH_cyto.CX_report.txt")
Reading file: M82_0h_CHH_cyto.CX_report.txt
Read 268714657 records
Finished reading file: M82_0h_CHH_cyto.CX_report.txt
> DMRsBinsCHH <- computeDMRs(methylationDataList[["M82"]],
 methylationDataList[["clf"]],
 regions = NULL,
 context = "CHH",
method = "bins",
binSize = 500,
 test = "score",
pValueThreshold = 0.05,
 minCytosinesCount = 4,minProportionDifference = 0.4,minGap = 200,minSize = 50,minReadsPerCytosine = 4,cores=8)
Parameters checking ...
Error in .stopIfNotAll(c(!is.null(methylationData), is(methylationData,  :
  object 'methylationDataList' not found
> methylationDataMut <- readBismark("clf_0h_CHH_cyto.CX_report.txt")
Reading file: clf_0h_CHH_cyto.CX_report.txt
Read 268714657 records
Finished reading file: clf_0h_CHH_cyto.CX_report.txt
> methylationDataList <- GRangesList("M82" = methylationDataWT,"clf" = methylationDataMut)
> DMRsBinsCHH <- computeDMRs(methylationDataList[["M82"]],
 methylationDataList[["clf"]],
 regions = NULL,
 context = "CHH",
 method = "bins",
 binSize = 500,
 test = "score",
 pValueThreshold = 0.05,
 minCytosinesCount = 4,minProportionDifference = 0.4,minGap = 200,minSize = 50,minReadsPerCytosine = 4,cores=8)
Parameters checking ...
[2]+  Killed                  R
Killed`

**Comment by nrzabet** [comment]
Depends on the size of the genome, you might need higher memory being allocated. 

1. What genome are you looking at? 
2. if don't have enough memory, you could load one chromosome at a time.

**Comment by sanchari24** [comment]
It is the tomato genome. It works when I do chromosome wise analysis
